### ISSUE TITLE
Figure out where to store discussion section answer keys

### ISSUE THREAD

**Issue by ryoliver** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#10]
Each discussion section will get a page with instructions (example [here](https://eds-221-programming-essentials.github.io/course-materials/eod-practice/eod-day1.html)). We should also include an answer key that becomes visible after discussion section. 

I propose creating files in the `course-materials/discussion` folder with naming convention `week#-discussion-answer-key.qmd`

Not sure of the best place to link to them on the course website. Maybe as a link on the top of each of the discussion section pages? 

@avidalmeza @julietcohen any thoughts?

**Comment by julietcohen** [comment]
I like the idea of having the title explicitly label the doc as an answer key. With 10 docs already loose in the `course-materials/discussion` dir, I wonder if it will get chaotic with an additional 10. It may be cleaner to put the answer keys in a new subdirectory `course-materials/discussion/answer-keys`

Including a link to the answer keys at the top of the discussion section pages sounds fine, I can't imagine a better place. I'll take a look around when the website is back up.

**Comment by ryoliver** [comment]
Hmmm... good point. To simplify things, I wonder if we could just include the answers at the bottom of the page nested in a callout box. We could comment that section out before discussion section and un-comment it after discussion section.

**Comment by julietcohen** [comment]
If I understand your suggestion correctly, that means the answer key would be present in the qmd doc but not the rendered HTML. The course website repo is public within the course org where students will be added, so I think students would technically be able to peek at the qmd in the repo  and see the commented out code if they're being sneaky. Please correct me if I'm wrong though!

**Comment by avidalmeza** [comment]
Since discussion sections will be interactive and graded on attendance, I wouldn't think there's an incentive for students to be sneaky. Maybe we could include the answers in code chunks that are set to `eval = FALSE`? I also like the subdirectory option though.

**Comment by ryoliver** [comment]
I agree @avidalmeza. Since discussion sections aren't graded I don't think we need to worry too much. (I'm trying to instill a "you get what you put into it" philosophy). I think the easiest solution would be to include the code in callout boxes that are collapsed by default. That way students have to click to reveal the answers, but they're all there. 

My previous suggestion to update the rendered version after discussion would require rebuilding the website every week. From experience, it's annoying to have to remember to do small tasks like that every week, so let's try including the answers in callout boxes and see how it goes!
