### ISSUE TITLE
Week 2: Integrate real world vector datasets: GBIF for points, lines and polygons

### ISSUE THREAD

**Issue by julietcohen** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#11]
The [Week 2 lab](https://github.com/EDS-223-Geospatial/EDS-223-Geospatial.github.io/blob/main/course-materials/labs/week2.qmd) works with vector data. A useful real world point dataset would be wildlife observations for several species from the [Global Biodiversity Information Facility](https://www.gbif.org/) (GBIF) API. Each species' data should be pulled from the API, concatenated into one geodataframe, cleaned, and saved as a new geospatial file (shapefile/gpkg?) to be read into the lab for plotting and exploration in the section "Handling sf Objects". In addition, basemaps and/or interesting polygons with spatial overlap can be saved for mapping throughout the lab. It would be especially useful for these geospatial files to have different CRS so the students practice transformations. 

The script for creating this dataset can be added to the repo and included in the gitignore so adjustments can be made.

**Comment by avidalmeza** [comment]
- [ ] Grab species occurrence data for Colombia from GBIF
- [ ] Grab roads data from OpenStreetMap
- [ ] Grab ecoregions of Colombia data by the The Nature Conservancy/NatureServe  
- [ ] Write instructions for discussion section and cover: CRS transformations and attribute manipulations
- [ ] Write answer key for discussion section
