### ISSUE TITLE
Add a rubric to the Assignments tab

### ISSUE THREAD

**Issue by julietcohen** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#14]
As a starting place, use [this rubric](https://docs.google.com/document/d/1c7uhJuDt3qq8Kg51wiM2OyDJR_xv7h5peBcq2A0k98g/edit) from the previous year. This document should clarify expectations for students to include good practices in data science such as:

- **code execution checks** that the code doing what you intended it to do
  - example: CRS transformation was successful
- **warning messages** and/or **error messages** in functions
- **documentation** such as:
  - section headers
  - descriptions for an analysis step
  - plot/output interpretation
  - data citations

These components help an assignment follow the "good" examples available on the course website (see [issue#12](https://github.com/EDS-223-Geospatial/EDS-223-Geospatial.github.io/issues/12))

**Comment by ryoliver** [comment]
Add good/bad examples from Resources page to Assignments page in a "Rubric" section
