### ISSUE TITLE
Update discussion section details

### ISSUE THREAD

**Issue by ryoliver** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#36]
Discussion section details [here](https://eds-223-geospatial.github.io/#weekly-schedule) are out of date. Need to update with the following:

Wednesday 2:00-2:50 pm in Bren Hall 3022
Wednesday 3:00-3:50 pm in Bren Hall 3022

**Comment by julietcohen** [comment]
[Pull request](https://github.com/EDS-223-Geospatial/EDS-223-Geospatial.github.io/pull/39) just merged :)
