### ISSUE TITLE
Hide course materials for weeks 3-10 in drop down tab right before quarter starts

### ISSUE THREAD

**Issue by julietcohen** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#37]
Merge branch `cohen-hide-weeks3-10` into `main` right before quarter starts to restrict students from viewing materials that may not be finished yet. This will require the website to be rebuilt by the end of the second week of the quarter to make at least week 3 visible.

**Comment by ryoliver** [comment]
FYI, we can remove the week 7 tab because there's no class that week
