### ISSUE TITLE
Week 4 discussion: small improvements to answer key and instructions

### ISSUE THREAD

**Issue by julietcohen** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#65]
The following changes are recommended:

- double check that the filepaths for importing data match where you expect students to store the data files
- delete the extra package import chunk 
  - side note: If students do not already have the package `spDataLarge` installed, they may have to install using `install.packages('spDataLarge', repos='https://nowosad.github.io/drat/', type='source')` 
- for the answer key under section `Find Correlation Between NDWI and NDVI`, it would be helpful to provide a more informative label the two plots that are currently both labeled as `lyr1`
- the variable `peru_dem` in the next section `Find Distances Across All peru_dem Cells` needs to be defined before it is called in the function `aggregate` or else the chunk errors
- similarly to the `lyr1` plots, the final chunk’s output plots would also be easier to understand with distinct labels
- the wording of instruction 3 is a little confusing since it has 2 distinct parts but is organized as one task with a note and a bullet. Maybe just make this 2 parts a) and b)

**Comment by avidalmeza** [comment]
Thanks for the feedback @julietcohen!

- [ ]  Double check filepaths for data import
- [ ]  Provide a more informative label for *Find Correlation Between NDWI and NDVI*
- [ ]  Define the variable `peru_dem` for *Find Distances Across All `peru_dem` Cells*
- [ ]  Add distinct labels to the final chunk’s output plots
- [ ]  Update wording of instruction 3. Split into Part A and Part B?
- [ ]  Add note about `install.packages('spDataLarge', repos='https://nowosad.github.io/drat/', type='source')`
