### ISSUE TITLE
Week 2 discussion feedback

### ISSUE THREAD

**Issue by julietcohen** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#67]
Week 2 discussion looks great and is very clear. Some small recommendations:

- double check that the filepaths for importing data match where you expect students to store the data files
- include `library(here)` if you want them to use that package
- in the answer key, visually speaking, having the `package::function` syntax so often can be a little distracting when reading code in chunks where it is repeated for the same package like the `tmap` one at the end. Ruth's feedback: "_maybe as a guideline we should try to include that syntax in the first week they are introduced to a package and afterwards can omit it?_"

**Comment by avidalmeza** [comment]
- [ ] Double check filepaths for data import
- [ ] Include library(here)
- [ ] Remove package::function syntax from code chunks, instead include in instructions
