### ISSUE TITLE
Add link to slides for week 1

### ISSUE THREAD

**Issue by ryoliver** [EDS-223-Geospatial/EDS-223-Geospatial.github.io#71]
@julietcohen could you add the following link to slides for week 1?

Link:
https://docs.google.com/presentation/d/1WWYmnEuwRApjeYMHpaAVZf1qMDOxt5jYblzeo5yYQ8Q/present?usp=sharing

Line:
https://github.com/EDS-223-Geospatial/EDS-223-Geospatial.github.io/blob/ec0f64c6ae3a99cdf758bf063f4d74a59312ec5c/course-materials/week1.qmd#L22

**Comment by julietcohen** [comment]
Will do!
